### ISSUE TITLE
https://readable.shuttleapp.rs/ status 503

### ISSUE THREAD

**Issue by Alanon202** [mre/readable#11]
{"message":"project not ready","status_code":503}

**Comment by mre** [comment]
Huh, let me have a look. Guess I need to update the shuttle version as the folks made some changes recently.

**Comment by mre** [comment]
It's back up again. Needed to update the shuttle version and do a fresh deploy. Thanks for the heads-up. 👍

**Comment by Alanon202** [comment]
@mre Sorry to re-open the thread, now it says: could not find service: readable

**Comment by mre** [comment]
Alright, I pushed it back up again. Let's see how long it sticks this time. 🤔 No changes on my end...

**Comment by Alanon202** [comment]
@mre ...aaaand it’s down again. 

"503 project not ready"

**Comment by mre** [comment]
Not sure what's going on there. Seems like I have to set up my own monitoring at some point. :/
Thanks again for the notification. 👍

**Comment by Alanon202** [comment]
@mre Sorry to bother you again, but... 503.

**Comment by mre** [comment]
Thanks. It's up again... but who knows for how long. 😆 Enjoy it while it lasts. 🍸

**Comment by Alanon202** [comment]
@mre Not that I’ve been using it all this time, but the first chance I got, and it’s down.

**Comment by mre** [comment]
There's a fundamental problem here. Need to ask on Discord. I know that they currently restructure the service and move towards webassembly. I doubt that the platform in general is as unstable as this single deployment, so maybe it's an outdated library or there's an issue with my account. No clue.

**Comment by whzard** [comment]
Sorry, but this just happened again, same error: `{"message":"project not ready","status_code":503}`

**Comment by mre** [comment]
Terribly sorry about this. I updated all dependencies and made it work again. https://github.com/readable-app/readable/commit/36297da63bfccdd37756e4d4b418c2d41407b419
But I removed self-hosted support, because I don't have time to maintain that. So it's only available on https://readable.shuttleapp.rs/ anymore.

Thanks @wheezard for the heads-up. ❤️
