### ISSUE TITLE
Service is down long-time

### ISSUE THREAD

**Issue by freelon** [mre/readable#13]
The service keeps responding with
```
{"message":"project not ready. Try running `cargo shuttle project restart`.","status_code":503}
```

Maybe a restart will help? 😎

**Comment by mre** [comment]
The project runs locally, but when I run `cargo shuttle project restart`, I get an error:

```sh
~/C/p/r/readable ❯❯❯ cargo shuttle project restart                                                                                                                                                     
Project "readable" is destroyed
Run `cargo shuttle project start` to recreate project environment on Shuttle.
Project "readable" is errored
        message: project did not become healthy in time
Your project will sleep if it is idle for 30 minutes.
To change the idle time refer to the docs: https://docs.shuttle.rs/getting-started/idle-projects

Run `cargo shuttle deploy --allow-dirty` to deploy your Shuttle service.
```

Tried yesterday and today; same result.

**Comment by freelon** [comment]
Uh then maybe it's a too old shuttle dependency version by now.. I'll see if it runs locally for me or provide a PR if I can fix it by updating the dependencies.

**Comment by freelon** [comment]
I can run it without problems (locally and also deployed on shuttle under a different name).

**Comment by mre** [comment]
Oh, interesting. I don't know how to "free" the old name. Checked the Shuttle UI and can't find a button.

**Comment by mre** [comment]
Okay, it's finally up again.  https://readable.shuttleapp.rs

Here's what I did for future reference:

```sh
cargo shuttle project stop --name readable
cargo shuttle project list
cargo shuttle clean
cargo shuttle project restart
cargo shuttle deploy --allow-dirty
```

In general, I'd say it's safer to run a custom version of readable somewhere. 😅 
Thanks for reporting, @freelon. 👍
