### ISSUE TITLE
Tool not working

### ISSUE THREAD

**Issue by skynet2982** [mre/readable#14]
Hi 👋

The tool seems to be ko at the moment.

Also it could be something good to provide instructions for self-host to avoid this problem. Maybe you could work on a docker image for this tool !

Regards,
Robin

**Comment by mre** [comment]
It's working again after some cleanup and redeployment. See https://github.com/readable-app/readable/commit/832bc9e347e17bc4a650eecab66799f2c9155126 for the changes.
Thanks for the heads-up. 😊

**Comment by mre** [comment]
The service used to be self-hostable, but I removed that feature, because I didn't want to invest the time to keep the two versions in sync. The last self-hostable version is https://github.com/readable-app/readable/tree/b1b0afb43e3d9db7c71e5e65ffa6973c3e79fc00 if you want to maintain/fork that. 😄

**Comment by skynet2982** [comment]
Thanks. It works great doing:
`cargo build --release --features local &&
./target/release/readable`

Do you know how to Dockerize it ? I did:

```
FROM rust:latest
WORKDIR /app
COPY . .
RUN cargo build --release --features local
CMD ["./target/release/readable"]
```

But it doesnt work (no error but I can't access the service in my browser).

**Comment by mre** [comment]
How did you start the container?
You might need to change this line from 127.0.0.1 to 0.0.0.0:

https://github.com/readable-app/readable/blob/b1b0afb43e3d9db7c71e5e65ffa6973c3e79fc00/src/bin.rs#L36

And then it should run on port 8000, but you might need to mount that port like

```sh
docker run -p8000:8000 yourimage
```

**Comment by skynet2982** [comment]
Thanks :)
